### ISSUE TITLE
Make it a proper layer

### ISSUE THREAD

**Issue by otavio** [monkey/monkey-yocto#1]
Hello,

The idea of providing ready to use recipes is very keen however this should be done in a proper expected way. I see two issues:
- lack of conf/layer.conf: so it is not a proper layer and requires the manual copy of the recipes
- naming: it should be renamed to meta-monkey

Another possibility, as it is just a recipe, is to submit it to meta-webserver and avoid the maintenance hassle at all. You, or someone else, will need to be preparing updates whenever a release is made.

**Comment by edsiper** [comment]
it's already there:

http://git.openembedded.org/meta-openembedded/tree/meta-webserver/recipes-httpd/monkey

we maintain this repo as the source for the work pushed to meta-openembedded

**Comment by otavio** [comment]
So we have a problem. Your leading page, in the project website, does not cite or refer to the layer.

To be honest it seems like work duplication to have same content in two layers but this is not my call.

Anyway I think the communication in the project page could be improved as I didn't see any reference for the layer.
